# divmod()


divmod()函数(使用在两数相加得情况下)：divmod(divident, divisor)参数：divident被除数。divisor除数。显示 5 除以 2 的商和余数：x = divmod(5, 2)  --输出x--(2, 1)返回(a//b, a%b)

In [1]:
m, n = divmod(5, 2)
# print(m, n)
m = divmod(5, 2)

# 万能lambda()函数

Lambda函数也被称为匿名(没有名称)函数，它直接接受参数的数量以及使用该参数执行的条件或操作，该参数以冒号分隔，并返回最终结果。

In [ ]:
#结合使用

# map()函数

map()函数会根据提供的函数对指定的序列进行映射
比如：

In [5]:
list1 = '1,2,3,4,5'
def square(x):
    return x**2
print(list(map(int, list1.split(','))))#将字符串中的数字放到列表中输出
print(list(map(square, list(map(int, list1.split(','))))))#将字符串中的数字进行平方处理，以列表输出
print(list(map(lambda x:x**2,list(map(int, list1.split(','))))))#将字符串中的数字进行平方处理，以列表输出

[1, 2, 3, 4, 5]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


# format函数

1.format函数：字符串的格式化输出，使用{}或者{:}作为占位符，可以代替之前版本的%  
2.{:d}、{:06d} 代表输出的是十进制数值，接收的数字是int类型的。如果变量是其他类型的，会报错  
3.{:f}、 {:.2f}输出为浮点数。接受的是float类型的。f前加数字，则表示需要保留的位数。如果接收的是其他数据类型，则会报错。

变量与占位符对应:  
a.占位符内，没有任何内容时，则按照变量的顺序，一一对应占位符。  
b.占位符内，使用数字，调整变量填充顺序。{}中的数字，代表的是变量的索引。需要注意，变量的索引是从0开始的。{}中输入数字时，不要大于索引，否则会报错。  
c.可以进行关键字进行变量对应填充。使用这个方法，需要注意，{}中的关键字一定要和format函数中的关键字一样。  
d.如果是列表，还可以使用列表形式的索引。  
e.format函数中，还可以使用字典，在{}中输入字典的key，取出对应的值。但是在format函数中，字典需要加上**    

3.需要注意的点：占位符可以比变量值少，但不能比变量值多，否则会报错。

In [ ]:
name = '张三'
age = 18
address = '北京市'
sex = '男'
float_num = '123.123456'
print('名字是:{}'.format(name))#1
print('名字是:{:}'.format(name))#1
print('年龄是:{:d}'.format(age))#2
print('年龄是:{:03d}'.format(age))#2
print('输出一个浮点的数字:{:f}'.format(float_num))
print('输出浮点数字,保留3位小数:{:.3f}'.format(float_num))

# a.有多个值时，{}没有值，则按顺序一一对应填充
print("姓名：{:s} \n年龄:{} \n地址:{} \n".format(name, age, address))
# b.当{}中存在数字时，数字对应变量的索引，会按照数字取format函数中的值进行填充。需要注意，索引的值是从0开始。{}中的数字，不能超过变量的索引，否则会报错。
print("姓名：{1} \n年龄:{2} \n地址:{0} \n".format(name, age, address))
#c.注意关键词要一致
print("我的名字是{name},年龄是：{age}".format(name='张三', age=18))
#d.定义一个列表
list1 = ['张三', 18]
print('我的名字是{0[0]}, 年龄是{0[1]}'.format(list1))
#e.定义一个字典
dict1 = {"name": "张三", "age": 18}
print("我的名字是：{name}，年龄是：{age}".format(**dict1))

# {}占位符，要比format函数的变量少。否则会报错
print("姓名：{} \n年龄:{} \n地址:{} \n性别:{}".format(name, age, address))  # 有4个占位符，三个变量，则报错

print("姓名：{} \n年龄:{} \n地址:{} \n".format(name, age, address, sex))  # 有3个占位符，4个变量，则不会报错


# 去掉字符串前后空格

In [ ]:
str1 = ' Hello World '
print(str1.rstrip())#去除字符串前面的空格
print(str1.lstrip())#去除字符串后面的空格
print(str1.strip())#去除字符串前后面的空格


# 列表list()函数

In [ ]:
list1 = ['Tom', 'Allen']
list1.remove('Tom')#列表元素的删除
list1.append('John')#列表元素的增加

# print()


In [1]:
str1 = 'asdf'
print(str1*100)#不用循环输出一个字符串多遍

asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf


# 大小写字母转换

upper()和lower()函数只能让其整体大小写转换

capitalize()函数可以将字符串的首字母的开头转换为大写，其他为小写

title()函数使字符串的所有单词转为首字母转换为大写，其他为小写

In [3]:
str_1 = 'niu'
str_2 = 'NIU'
str_3 = 'niu niu'
print(str_1.upper())
print(str_2.lower())
print(str_3.capitalize())
print(str_3.title())


NIU
niu
Niu niu
Niu Niu


# 字符串分割

str.split()分割会得到一个列表，后面中可以确定按照什么分割，比如str.split(';')就是按照分号分割，还可以限定最大分割次数，比如str.split(';',1)，即分割一次，后面的会不分割

In [4]:
str_1 = 'niu niu niu'
print(str_1.split())

['niu', 'niu', 'niu']


还可以使用re库的分割来，可以使用正则化来进行多种多样的分割，比如：

In [6]:
import re
s = 'a123b456c789d'
print(re.split(r'\d+',s))#这个是使用正则表达式让一个或多个连续的数字作为分隔符
print(re.split(r'(\d+)',s))#可以分割一个包含数字和字母的字符串，并保留数字，但是这个是数字串是数字串，字母是字母


['a', 'b', 'c', 'd']
['a', '123', 'b', '456', 'c', '789', 'd']


# input() 和 raw_input()

raw_input()用来获取控制台的输入，该函数会将所有输入作为字符串看待，返回 string 类型，已被弃用

input()接受一个标准输入数据，返回为 string 类型，对待纯数字输入时具有自己的特性，它返回所输入的数字的类型（ int, float ）

In [3]:
#a = raw_input("input:")
#type(a)
#print(a)
b = input("input:")
type(b)
print(b)

# float中的数变为两位小数

方法一：'%',输出四舍五入的结果
方法二：round,输出四舍五入的结果

In [ ]:
num = 2.3456789
print('%.2f'%num)
print('%.3f'%num)
print('%.4f'%num)
print(round(2.25,1))
print(round(2.125,2))
print(round(2.8756,3))

# 浮点数的字符串转换为整数

不能直接转换为int，应该先转换为float再转成int

In [ ]:
i = 123465.416546
print(int(float(i)))

# int()函数的其他用法

In [5]:
#int()方法的语法是int(x,base)，这里的base指的是进制数，默认10进制,返回的是一个整数类型
#16进制数字转换为10进制就可以写成：
num16 = 'AB11'
print(int(num16, 16))

43793


# 格式并不同

输出print()中逗号，会自动空格，不能像下面这个一样，如果想换行应该重新其一行

In [6]:
print(a,'\n',b)#这样会使得输出结果a后面自带一个空格

NameError: name 'a' is not defined

# range()函数

range()函数返回的结果并不是列表，而是一个range类型的整数序列的对象 

<class 'range'>,但是可以利用list函数返回

range本身也是一个迭代器类似于zip


In [ ]:
range(10)#从0到10------[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
range(1,11)#从1到11------[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
range(0,30,5)#步长为5从0到30------[0, 5, 10, 15, 20, 25]
range(0,-10,-1)#负数------[0, -1, -2, -3, -4, -5, -6, -7, -8, -9]
range(0)#------[]
range(1,0)#------[]

# Numpy函数

创建数组

In [ ]:
#使用array创建：
list01 = [1,2,3,4]
array01 = np.array(list01)
#使用array创建二维数组：
list02 = [[1,2,3,4],[5,6,7,8]]
array02 = np.array(list02)
#使用array创建三维数组
list03 = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
array03 = np.array(list03)

In [ ]:
#使用arange创建：arange(start,stop,step,dtype) 
'''
1.不写start，默认从0开始
2.左开右闭
3.step步长，不写默认是1
'''
#创建一维数组：
a = np.arange(10) #[0 1 2 3 4 5 6 7 8 9]
a = np.arange(2,10) #[2 3 4 5 6 7 8 9]
a = np.arange(1,10,2) #[1 3 5 7 9]
a = np.arange(1,10,2,dtype = float)
#创建二维数组：
b = np.arange(12).reshape(3, 4)#后面的shape模型必须符合前面的大小

In [ ]:
#使用random创建数组
np.random.random(size)#生成0到1之间的随机数
np.random.randint(low, high = None, size = None, dtype = "l")#生成随机的整数np.random.randint(2, size=10)，dype可选int64等
np.random.randn(d0,d1,d2,d3...)#生成标准正态的随机数(期望为0，方差为1)
np.random.normal(locscale,size)#生成正态分布（指定期望和方差）
np.random.uniform(low,high,size)#生成均匀分布的随机数
np.random.shuffle()#随机打乱顺序
np.random.seed()#设置随机数种子
np.random.sample(size)#生成随机的浮点数
#创建一维数组
array01 = np.random.random(size = 4)#[0.13475357 0.8088961  0.52055803 0.49706622]
#创建二维数组
array02 = np.random.random((3,4))
#创建三维数组
array03 = np.random.random((2,3,4))

#创建一维数组
array01 = np.random.randint(1,11,10)#1-10
#创建二维数组
array02 = np.random.randint(1,11,(3,4))#(3，4)为形状
#创建三维数组
array03 = np.random.randint(1,11,(2,3,4))

In [ ]:
#生成均匀分布的随机数
np.random.uniform(low,high,size)
#四个数据几乎不会相差太多比较均匀
array01 = np.random.uniform(size= 4)
array02 = np.random.uniform(size= (2,4))
array03 = np.random.uniform(high=3)

In [ ]:
#随机打乱顺序
np.random.shuffle(array)
array01 = np.array([2,5,6,7,3])
np.random.shuffle(array01)

In [ ]:
#设置随机数种子
np.random.seed()
#从每堆种子里选出来的数都是不会变的，从不同的堆里选随机种子每次都不一样，若想每次都能得到相同的随机数，每次产生随机数之前，都需要调用一次seed()
np.random.seed(1)
array01 = np.random.randint(1,10,size= 5)
np.random.seed(1)
array02 = np.random.randint(1,10,size = 5)

In [ ]:
#生成随机的浮点数，返回半开区间 [0.0, 1.0) 之间随机的浮点数。
np.random.sample(size) #注意，这个np.random.sample和random库里的random.sample不同

In [ ]:
#创建指定大小的数组，数组以0填充，下面的order是使其按行或者按列
np.zeros(shaps,dtype=float,order="C") 
array01 = np.zeros(5) #[0. 0. 0. 0. 0.]
array02 = np.zeros(5,dtype="int32")  #[0 0 0 0 0]
array03 = np.zeros((2,5),dtype="int32") 

In [ ]:
#使用linscpace是用于创建等差数列，常看到的一般是三个参数，分别是：起始值、终止值（默认包含自身）、数列个数
#另外有一个参数endpoint，用于决定是否包含终止值，如果不设置这个参数，默认为是True
array01 = np.linspace(1,10,5)#从1-10，生成5个数据
array02 = np.linspace(1,10,5,endpoint=True)#把10包含进去
array03 = np.linspace(1,10,5,endpoint=False)#把10不包含进去
array04 = np.linspace(1,10,5,retstep=True)#显示间距
array05 = np.linspace(1,10,5,dtype="int32")

np.stack()函数

In [ ]:
#stack为堆叠，这个函数主要有两个参数。np.stack([arrays1,array2,array3],axis=0)。
#第一个是需要堆叠的多个数组，采用列表的形式输入，
#第二个参数是axis，这个参数表示从哪一个维度进行堆叠以及堆叠的内容，这个维度是相对于堆叠的数组来说的。整个函数的输出为一个新数组。
array01 = np.array([i for i in range(12)]).reshape(3,4)
array02 = np.array([i for i in range(12,24)]).reshape(3,4)
array03 = np.array([i for i in range(24,36)]).reshape(3,4)
'''
a= [[ 0  1  2  3]
    [ 4  5  6  7]
    [ 8  9 10 11]]
b= [[12 13 14 15]
    [16 17 18 19]
    [20 21 22 23]]
c= [[24 25 26 27]
    [28 29 30 31]
    [32 33 34 35]]
'''

'''
axis = 0:  表示它堆叠方向为第0维,堆叠的内容为数组第0维的数据.前面说了第0维是相对于堆叠的数组而言的,
而这里数组的第0维其实就是整个3x4的数组(其中第1维为行,第2维为某一行中的一个值,
这里有一个层层深入的感觉),所以就是以整个3x4的数组为堆叠内容在第0维上进行堆叠,
等到的结果就是一个3x3x4的新数组。再通俗一点,就是将array01,array02,array03分别作为堆叠内容进行堆叠得到3x3x4的输出。
'''
new_array = np.stack([array01,array02,array03],axis=0)
'''
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]
 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]
 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
'''

'''
axis = 1:  和刚才的解释一样,axis为1表示堆叠的方向为3x4数组的第1维(行),堆叠内容也为3x4数组的第1维的数据。
而3x4的数组的第1维就是它的行,以数组a为例,它的堆叠数据分别是[0 1 2 3],[ 4 5 6 7],[ 8 9 10 11]。
所以array01,array02,array03三个数组在第1维上堆叠后的结果就是上面的输出结果。
'''
new_array = np.stack([array01,array02,array03],axis=1)
'''
[[[ 0  1  2  3]
  [12 13 14 15]
  [24 25 26 27]]
 [[ 4  5  6  7]
  [16 17 18 19]
  [28 29 30 31]]
 [[ 8  9 10 11]
  [20 21 22 23]
  [32 33 34 35]]]
'''

'''
当axis=2时,表示堆叠内容是3x4数组的第二维的数据(数组中某一行的某个值),堆叠方向为第二维(也就是先补全某一行)。
对于数组a,第2维的第一个值为0,b为12,c为24,所这三个值组成堆叠后的新数组的一行,以此类推,最终可以得到下面的输出结果。
'''
new_array = np.stack([array01,array02,array03],axis=2)
'''
[[[ 0 12 24]
  [ 1 13 25]
  [ 2 14 26]
  [ 3 15 27]]
 [[ 4 16 28]
  [ 5 17 29]
  [ 6 18 30]
  [ 7 19 31]]
 [[ 8 20 32]
  [ 9 21 33]
  [10 22 34]
  [11 23 35]]]
'''